version: '3.6'

services:
  ecommerce-service-registry:
    image: srinivasans611/ecommerce-service-registry
    container_name: ecommerce-service-registry-1
    ports:
      - 5000:5000
    networks:
      - ecommerce_network
  ecommerce-user-service:
    image: srinivasans611/ecommerce-users
    container_name: ecommerce-users-1
    ports:
      - 5001:5001
    depends_on:
      - ecommerce-service-registry
    environment:
      eureka.client.serviceUrl.defaultZone: http://ecommerce-service-registry:5000/eureka
    networks:
      - ecommerce_network
      
  ecommerce-orders-service:
    image: srinivasans611/ecommerce-orders
    container_name: ecommerce-orders-1
    ports:
      - 5003:5003
    environment:
      eureka.client.serviceUrl.defaultZone: http://ecommerce-service-registry:5000/eureka
    networks:
      - ecommerce_network
  
  ecommerce-products-service:
    image: srinivasans611/ecommerce-products
    container_name: ecommerce-products-1
    ports:
      - 5002:5002
    environment:
      eureka.client.serviceUrl.defaultZone: http://ecommerce-service-registry:5000/eureka
    networks:
      - ecommerce_network
      

networks:
  ecommerce_network:
    name: ecommerce_network