spring:
  application:
    name: ecommerce-service-registry

server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka
    registerWithEureka: false
    fetchRegistry: false
    instance:
      prefer-ip-address: true
      hostname: localhost



